[pytest]
DJANGO_SETTINGS_MODULE = kiosk.settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short --disable-warnings --reuse-db
testpaths = tests
norecursedirs = venv .git __pycache__ node_modules
