# Generated by Django 6.0.6 on 2026-07-28 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_useractivity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSizeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_upload_size_mb', models.IntegerField(default=100, verbose_name='حداکثر حجم آپلود (مگابایت)')),
                ('max_download_size_mb', models.IntegerField(default=200, verbose_name='حداکثر حجم دانلود (مگابایت)')),
                ('warning_threshold_mb', models.IntegerField(default=50, verbose_name='آستانه هشدار حجم (مگابایت)')),
                ('allow_large_files', models.BooleanField(default=True, verbose_name='اجازه آپلود فایل\u200cهای بزرگ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی توسط')),
            ],
            options={
                'verbose_name': 'تنظیمات حجم فایل',
                'verbose_name_plural': 'تنظیمات حجم فایل',
                'db_table': 'file_size_settings',
            },
        ),
    ]
