# Generated by Django 6.0.6 on 2026-07-31 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_filesizesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', max_length=20)),
                ('total_users', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulk_assignments', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_assignments', to='auth.group')),
                ('users', models.ManyToManyField(related_name='bulk_role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اختصاص نقش گروهی',
                'verbose_name_plural': 'اختصاص نقش\u200cهای گروهی',
            },
        ),
        migrations.CreateModel(
            name='RolePasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_password_length', models.IntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_digit', models.BooleanField(default=True)),
                ('require_special_char', models.BooleanField(default=False)),
                ('require_lowercase', models.BooleanField(default=True)),
                ('password_expiry_days', models.IntegerField(blank=True, default=90, null=True)),
                ('max_login_attempts', models.IntegerField(blank=True, default=5, null=True)),
                ('role', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='password_policy', to='auth.group')),
            ],
            options={
                'verbose_name': 'سیاست رمز عبور نقش',
                'verbose_name_plural': 'سیاست\u200cهای رمز عبور نقش\u200cها',
            },
        ),
        migrations.CreateModel(
            name='RolePermissionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(related_name='templates', to='auth.permission')),
            ],
            options={
                'verbose_name': 'قالب دسترسی نقش',
                'verbose_name_plural': 'قالب\u200cهای دسترسی نقش',
            },
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اختصاص نقش',
                'verbose_name_plural': 'اختصاص نقش\u200cها',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
