# Generated by Django 6.0.6 on 2026-10-01 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bulkroleassignment_rolepasswordpolicy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('conversation_type', models.CharField(choices=[('file_summary', 'خلاصه فایل'), ('file_question', 'سوال درباره فایل'), ('user_analysis', 'تحلیل کاربر'), ('general_ask', 'سوال عمومی'), ('manual_analysis', 'تحلیل دستی فایل')], default='general_ask', max_length=30, verbose_name='نوع گفتگو')),
                ('question', models.TextField(blank=True, null=True, verbose_name='سوال کاربر')),
                ('answer', models.TextField(verbose_name='پاسخ هوش مصنوعی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_conversations', to='core.uploadedfile', verbose_name='فایل مرتبط')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'گفتگوی هوش مصنوعی',
                'verbose_name_plural': 'گفتگوهای هوش مصنوعی',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='core_aiconv_user_id_a181d8_idx'), models.Index(fields=['conversation_type', '-created_at'], name='core_aiconv_convers_c345a9_idx')],
            },
        ),
    ]
