# Generated by Django 6.0.6 on 2026-10-02 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_aiconversation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileAIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_json', models.JSONField(default=dict, verbose_name='تحلیل کامل JSON')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='خلاصه')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='دسته')),
                ('threat_level', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], default='low', max_length=20, verbose_name='سطح تهدید')),
                ('relevance_score', models.FloatField(default=0.0, verbose_name='امتیاز مرتبط بودن با نقش')),
                ('is_related', models.BooleanField(default=True, verbose_name='مرتبط با کاربر؟')),
                ('user_role_at_upload', models.CharField(blank=True, max_length=100, null=True, verbose_name='نقش کاربر در زمان آپلود')),
                ('top_topic', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع غالب')),
                ('model_used', models.CharField(blank=True, max_length=100, null=True, verbose_name='مدل استفاده\u200cشده')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان تحلیل')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='core.uploadedfile', verbose_name='فایل')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_analyses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تحلیل فایل',
                'verbose_name_plural': 'تحلیل\u200cهای فایل',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['user', '-analyzed_at'], name='core_fileai_user_id_d0bece_idx'), models.Index(fields=['is_related', '-analyzed_at'], name='core_fileai_is_rela_0d3aa6_idx'), models.Index(fields=['threat_level'], name='core_fileai_threat__91133d_idx')],
            },
        ),
    ]
