# Generated by Django 6.0.6 on 2026-10-02 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_fileaianalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehaviorAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_json', models.JSONField(default=dict, verbose_name='تحلیل کامل JSON')),
                ('total_files', models.IntegerField(default=0, verbose_name='تعداد کل فایل\u200cها')),
                ('related_files_count', models.IntegerField(default=0, verbose_name='فایل\u200cهای مرتبط')),
                ('unrelated_files_count', models.IntegerField(default=0, verbose_name='فایل\u200cهای غیرمرتبط')),
                ('suspicious_files_count', models.IntegerField(default=0, verbose_name='فایل\u200cهای مشکوک')),
                ('relevance_avg', models.FloatField(default=0.0, verbose_name='میانگین relevance')),
                ('related_percent', models.FloatField(default=0.0, verbose_name='درصد مرتبط')),
                ('suspicious_percent', models.FloatField(default=0.0, verbose_name='درصد مشکوک')),
                ('top_topics', models.JSONField(default=list, help_text='[{"name": "...", "count": N, "weight": 0.8}, ...]', verbose_name='موضوعات غالب (top 5)')),
                ('file_types_distribution', models.JSONField(default=dict, help_text='{"pdf": 10, "txt": 3, ...}', verbose_name='توزیع انواع فایل')),
                ('ai_summary', models.TextField(blank=True, null=True, verbose_name='خلاصه تحلیل AI')),
                ('last_analyzed_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تحلیل')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_analysis', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تحلیل رفتار کاربر',
                'verbose_name_plural': 'تحلیل\u200cهای رفتار کاربران',
                'indexes': [models.Index(fields=['-last_analyzed_at'], name='core_userbe_last_an_c62ad9_idx')],
            },
        ),
    ]
