# Generated by Django 6.0.6 on 2026-10-02 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userbehavioranalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان جلسه')),
                ('context_text', models.TextField(blank=True, default='', verbose_name='متن context ارسالی به FastAPI')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین به\u200cروزرسانی')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='ادمین')),
                ('files', models.ManyToManyField(blank=True, related_name='report_chat_sessions', to='core.uploadedfile', verbose_name='فایل\u200cهای انتخاب\u200cشده')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_chat_sessions_about_me', to=settings.AUTH_USER_MODEL, verbose_name='کاربر هدف (اختیاری)')),
            ],
            options={
                'verbose_name': 'جلسه چت گزارشات',
                'verbose_name_plural': 'جلسات چت گزارشات',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'ادمین'), ('assistant', 'هوش مصنوعی'), ('system', 'سیستم')], max_length=10, verbose_name='نقش')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('ai_response_json', models.JSONField(blank=True, default=dict, verbose_name='پاسخ کامل FastAPI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.reportchatsession', verbose_name='جلسه')),
            ],
            options={
                'verbose_name': 'پیام چت گزارشات',
                'verbose_name_plural': 'پیام\u200cهای چت گزارشات',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportchatsession',
            index=models.Index(fields=['admin', '-updated_at'], name='core_report_admin_i_3e39ac_idx'),
        ),
        migrations.AddIndex(
            model_name='reportchatmessage',
            index=models.Index(fields=['session', 'created_at'], name='core_report_session_108524_idx'),
        ),
    ]
