# Generated by Django 6.0.6 on 2026-09-18 19:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EngineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('last_check', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'وضعیت موتور',
                'verbose_name_plural': 'وضعیت موتورها',
            },
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash_sha256', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('running', 'در حال اجرا'), ('completed', 'تکمیل شده'), ('failed', 'خطا')], default='pending', max_length=20)),
                ('final_score', models.IntegerField(default=0)),
                ('is_threat', models.BooleanField(default=False)),
                ('severity', models.CharField(default='clean', max_length=20)),
                ('verdict', models.CharField(blank=True, max_length=200)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('completed_engines', models.IntegerField(default=0)),
                ('total_engines', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scanned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='av_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اسکن Multi-AV',
                'verbose_name_plural': 'اسکن\u200cهای Multi-AV',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EngineResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_name', models.CharField(max_length=50)),
                ('score', models.IntegerField(default=0)),
                ('threat', models.BooleanField(default=False)),
                ('details', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_results', to='multi_av.scanjob')),
            ],
            options={
                'verbose_name': 'نتیجه موتور',
                'verbose_name_plural': 'نتایج موتورها',
                'ordering': ['engine_name'],
                'unique_together': {('scan', 'engine_name')},
            },
        ),
    ]
