


"""
Django settings for kiosk project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-#rwi85^$@#7&s*$8at13z3h^6ot1(p4i0*!=0#^cp3gkmik68x'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'multi_av',
    'drf_yasg',
    'rest_framework',  
    'rest_framework.authtoken',  
    'django_celery_results'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',  # ✅ فعال شد
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'kiosk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'kiosk.wsgi.application'


# تنظیمات دیتابیس - استفاده از SQLite
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = '/static/'  # ✅ فقط این یک خط بماند
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]



# Media files (Uploaded files)
MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CSRF Settings
CSRF_COOKIE_SECURE = False

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',  # ✅ اضافه شد
    'http://127.0.0.1:8000',  # ✅ اضافه شد
    'http://localhost',
    'http://127.0.0.1',
    'http://192.168.1.100',
    'http://192.168.1.110',
    'http://10.135.0.129',
]


DATA_UPLOAD_MAX_NUMBER_FIELDS = None
DATA_UPLOAD_MAX_NUMBER_FILES = None

SESSION_EXPIRE_AT_BROWSER_CLOSE = True



# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': [
#         'rest_framework.authentication.SessionAuthentication',
#     ],
#     'DEFAULT_PERMISSION_CLASSES': [
#         'rest_framework.permissions.IsAuthenticated',
#     ],
#     'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
#     'PAGE_SIZE': 20,
#     'DEFAULT_RENDERER_CLASSES': [
#         'rest_framework.renderers.JSONRenderer',
#         'rest_framework.renderers.BrowsableAPIRenderer',
#     ],
#     'DEFAULT_PARSER_CLASSES': [
#         'rest_framework.parsers.JSONParser',
#         'rest_framework.parsers.FormParser',
#         'rest_framework.parsers.MultiPartParser',
#     ],
# }



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# Redirect URLs for login/logout
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'


MULTI_AV = {
    'ENABLED_ENGINES': ['clamav', 'yara', 'virustotal', 'ai', 'heuristic'],
    'VIRUSTOTAL_API_KEY': 'YOUR_API_KEY_HERE', 
    'CLAMAV_HOST': 'localhost',
    'CLAMAV_PORT': 3310,
    'THREAT_THRESHOLD': 50,        
    'CRITICAL_THRESHOLD': 80,  
    'WEIGHTS': {
        'clamav': 1.0,
        'yara': 1.2,
        'virustotal': 1.5,
        'ai': 0.8,
        'heuristic': 0.6,
    },
}

# ==================== Celery ====================
CELERY_BROKER_URL = 'amqp://admin:admin123@localhost:5672//'
CELERY_RESULT_BACKEND = 'rpc://'   # یا 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 600        # 10 دقیقه
CELERY_TASK_SOFT_TIME_LIMIT = 540
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_ACKS_LATE = True
CELERY_WORKER_MAX_TASKS_PER_CHILD = 50

# صف‌های جداگانه برای هر موتور
CELERY_TASK_ROUTES = {
    'multi_av.tasks.scan_with_clamav':    {'queue': 'av_clamav'},
    'multi_av.tasks.scan_with_yara':      {'queue': 'av_yara'},
    'multi_av.tasks.scan_with_virustotal':{'queue': 'av_virustotal'},
    'multi_av.tasks.scan_with_heuristic': {'queue': 'av_heuristic'},
    'multi_av.tasks.scan_with_ai':        {'queue': 'av_ai'},
    'multi_av.tasks.run_full_scan':       {'queue': 'av_orchestrator'},
}

# ==================== Multi-AV ====================
MULTI_AV = {
    'ENABLED_ENGINES': ['clamav', 'yara', 'virustotal', 'ai', 'heuristic'],
    'VIRUSTOTAL_API_KEY': 'YOUR_API_KEY_HERE',
    'CLAMAV_HOST': 'localhost',
    'CLAMAV_PORT': 3310,
    'THREAT_THRESHOLD': 50,
    'CRITICAL_THRESHOLD': 80,
    'WEIGHTS': {
        'clamav': 1.0,
        'yara': 1.2,
        'virustotal': 1.5,
        'ai': 0.8,
        'heuristic': 0.6,
    },
    'ENGINE_TIMEOUT': 300,
}

# Override DB for Docker
import os as _os
if _os.environ.get('DB_HOST'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': _os.environ.get('DB_NAME', 'fileapi'),
            'USER': _os.environ.get('DB_USER', 'fileapi'),
            'PASSWORD': _os.environ.get('DB_PASSWORD', 'fileapi123'),
            'HOST': _os.environ.get('DB_HOST', 'db'),
            'PORT': _os.environ.get('DB_PORT', '5432'),
        }
    }
